/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_bienvenue (void);
GtkWidget* create_window_gestionETS (void);
GtkWidget* create_window_ajouterETS (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_window_gestion_fiche_donneur (void);
GtkWidget* create_window_ajouter_fiche_donneur (void);
GtkWidget* create_window_modifier_fiche_donneur (void);
GtkWidget* create_window_list_RDV (void);
GtkWidget* create_window_moyenne_RDV (void);
GtkWidget* create_window_gestion_utilisateur (void);
GtkWidget* create_window_ajouter_utilisateur (void);
GtkWidget* create_window_modifier_utilisateur (void);
GtkWidget* create_window_gestion_don (void);
GtkWidget* create_window_filtrage (void);
GtkWidget* create_window_gestion_RDV (void);
GtkWidget* create_window_ajouter_RDV (void);
GtkWidget* create_window_liste_horraire (void);
GtkWidget* create_window_confirmation_RDV (void);
GtkWidget* create_window_modifier_RDV (void);
GtkWidget* create_affichage_don_ (void);
