/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_bienvenue;
  GtkWidget *window_gestionETS;
  GtkWidget *window_ajouterETS;
  GtkWidget *window_modifier;
  GtkWidget *window_gestion_fiche_donneur;
  GtkWidget *window_ajouter_fiche_donneur;
  GtkWidget *window_modifier_fiche_donneur;
  GtkWidget *window_list_RDV;
  GtkWidget *window_moyenne_RDV;
  GtkWidget *window_gestion_utilisateur;
  GtkWidget *window_ajouter_utilisateur;
  GtkWidget *window_modifier_utilisateur;
  GtkWidget *window_gestion_don;
  GtkWidget *window_filtrage;
  GtkWidget *window_gestion_RDV;
  GtkWidget *window_ajouter_RDV;
  GtkWidget *window_liste_horraire;
  GtkWidget *window_confirmation_RDV;
  GtkWidget *window_modifier_RDV;
  GtkWidget *affichage_don_;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  //window_bienvenue = create_window_bienvenue ();
  //gtk_widget_show (window_bienvenue);
  //window_gestionETS = create_window_gestionETS ();
  //gtk_widget_show (window_gestionETS);
  window_ajouterETS = create_window_ajouterETS ();
  gtk_widget_show (window_ajouterETS);
  //window_modifier = create_window_modifier ();
  //gtk_widget_show (window_modifier);
  /*
  window_gestion_fiche_donneur = create_window_gestion_fiche_donneur ();
  gtk_widget_show (window_gestion_fiche_donneur);
  window_ajouter_fiche_donneur = create_window_ajouter_fiche_donneur ();
  gtk_widget_show (window_ajouter_fiche_donneur);
  window_modifier_fiche_donneur = create_window_modifier_fiche_donneur ();
  gtk_widget_show (window_modifier_fiche_donneur);
  window_list_RDV = create_window_list_RDV ();
  gtk_widget_show (window_list_RDV);
  window_moyenne_RDV = create_window_moyenne_RDV ();
  gtk_widget_show (window_moyenne_RDV);
  window_gestion_utilisateur = create_window_gestion_utilisateur ();
  gtk_widget_show (window_gestion_utilisateur);
  window_ajouter_utilisateur = create_window_ajouter_utilisateur ();
  gtk_widget_show (window_ajouter_utilisateur);
  window_modifier_utilisateur = create_window_modifier_utilisateur ();
  gtk_widget_show (window_modifier_utilisateur);
  window_gestion_don = create_window_gestion_don ();
  gtk_widget_show (window_gestion_don);
  window_filtrage = create_window_filtrage ();
  gtk_widget_show (window_filtrage);
  window_gestion_RDV = create_window_gestion_RDV ();
  gtk_widget_show (window_gestion_RDV);
  window_ajouter_RDV = create_window_ajouter_RDV ();
  gtk_widget_show (window_ajouter_RDV);
  window_liste_horraire = create_window_liste_horraire ();
  gtk_widget_show (window_liste_horraire);
  window_confirmation_RDV = create_window_confirmation_RDV ();
  gtk_widget_show (window_confirmation_RDV);
  window_modifier_RDV = create_window_modifier_RDV ();
  gtk_widget_show (window_modifier_RDV);
  affichage_don_ = create_affichage_don_ ();
  gtk_widget_show (affichage_don_); */
	
  gtk_main ();
  return 0;
}

